repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace        # Remove trailing whitespace
      - id: end-of-file-fixer          # Ensure files end with newline
      - id: check-merge-conflict       # Check for merge conflicts
      - id: check-yaml                 # Validate YAML syntax
      - id: check-added-large-files    # Prevent large file commits
        args: ['--maxkb=5000']
      - id: mixed-line-ending          # Fix mixed line endings
        args: ['--fix=lf']
      # - id: no-commit-to-branch      # Prevent direct commits to master
      #   args: ["--branch", "master"]
